/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magazzinofumetti;

import java.util.HashSet;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author elsoft
 */
public class Anagrafiche extends javax.swing.JFrame {

    private int selId;
    private HashSet<Persona> elenco;

    /**
     * Creates new form Anagrafiche
     */
    public Anagrafiche() {
        initComponents();
        selId=-1;
        elenco=FunzioniDB.leggiPersone();
        aggiornaElenco();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtraPersoneButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        cognomeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        descrizioneTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        indirizzoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        cellulareTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        acquirenteCheckBox = new javax.swing.JCheckBox();
        venditoreCheckBox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        cancellaButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        elencoTable = new javax.swing.JTable();
        tuttiRadioButton = new javax.swing.JRadioButton();
        acquirentiRadioButton = new javax.swing.JRadioButton();
        venditoriRadioButton = new javax.swing.JRadioButton();
        nuovoButton = new javax.swing.JButton();
        filtraPersoneButtonGroup.add(tuttiRadioButton);
        filtraPersoneButtonGroup.add(acquirentiRadioButton);
        filtraPersoneButtonGroup.add(venditoriRadioButton);
        tuttiRadioButton.setSelected(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anagrafiche");

        jLabel1.setText("Nome");

        jLabel2.setText("Cognome");

        jLabel3.setText("Descrizione");

        jLabel4.setText("Indirizzo");

        jLabel5.setText("e-mail");

        jLabel6.setText("Telefono");

        acquirenteCheckBox.setText("Acquirente");

        venditoreCheckBox.setText("Venditore");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        annullaButton.setText("Annulla");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        cancellaButton.setText("Cancella");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annullaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancellaButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descrizioneTextField)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(cognomeTextField)))
                                .addComponent(jLabel4)
                                .addComponent(indirizzoTextField)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(cellulareTextField))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(acquirenteCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(venditoreCheckBox)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {annullaButton, cancellaButton, okButton});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cellulareTextField, cognomeTextField, emailTextField, nomeTextField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cognomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descrizioneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indirizzoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellulareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acquirenteCheckBox)
                    .addComponent(venditoreCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(annullaButton)
                    .addComponent(cancellaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        elencoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Cognome", "Decrizione"
            }
        ));
        elencoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elencoTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(elencoTable);

        tuttiRadioButton.setText("Tutti");
        tuttiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonsActionPerformed(evt);
            }
        });

        acquirentiRadioButton.setLabel("Acquirenti");
        acquirentiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonsActionPerformed(evt);
            }
        });

        venditoriRadioButton.setLabel("Venditori");
        venditoriRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonsActionPerformed(evt);
            }
        });

        nuovoButton.setText("Nuovo");
        nuovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuovoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tuttiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acquirentiRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(venditoriRadioButton))
                            .addComponent(nuovoButton))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuttiRadioButton)
                    .addComponent(acquirentiRadioButton)
                    .addComponent(venditoriRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuovoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annullaButtonActionPerformed

    
    private void elencoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elencoTableMouseClicked
        int row=elencoTable.getSelectedRow();
        if (row!=-1) {
            Persona selezionata=(Persona)elencoTable.getValueAt(row, 0);
            aggiornaDettagli(selezionata);
        }
    }//GEN-LAST:event_elencoTableMouseClicked

    private void radioButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonsActionPerformed
        String selezionato=evt.getActionCommand();
        switch (selezionato) {
            case "Tutti":
                elenco=FunzioniDB.leggiPersone();
                break;
            case "Acquirenti":
                elenco=FunzioniDB.leggiAcquirenti();
                break;
            case "Venditori":
                elenco=FunzioniDB.leggiVenditori();
                break;
            default:
                elenco=FunzioniDB.leggiPersone();
        }
        aggiornaElenco();
    }//GEN-LAST:event_radioButtonsActionPerformed

    private void nuovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuovoButtonActionPerformed
        svuotaDettagli();
        nomeTextField.requestFocus();
    }//GEN-LAST:event_nuovoButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String nome=nomeTextField.getText().trim();
        String cognome=cognomeTextField.getText();
        String descrizione=descrizioneTextField.getText().trim();
        String indirizzo=indirizzoTextField.getText().trim();
        String email=emailTextField.getText().trim();
        String telefono=cellulareTextField.getText().trim();
        String acquirente=(acquirenteCheckBox.isSelected())?"S":"N";
        String venditore=(venditoreCheckBox.isSelected())?"S":"N";
        String err="";
        if (nome.equals("")) {
            err+="Nome non può essere vuoto.\n";
        }
        if (cognome.equals("")) {
            err+="Cognome non può essere vuoto.\n";
        }
        if (email.equals("")&&telefono.equals("")) {
            err+="e-mail e telefono non possono\nessere entrambi vuoti.\n";
        }
        if (acquirente.equals("N")&&venditore.equals("N")) {
            err+="Devi selezionare almento uno\ntra acquirente e venditore.\n";
        }
        if (err.equals("")) {
            Persona pers=new Persona(nome,cognome, selId, descrizione,indirizzo, email, telefono, venditore, acquirente);
            if (pers.getId()>-1) {
                err=FunzioniDB.aggiornaPersona(pers);
            } else {
                err=FunzioniDB.inserisciPersona(pers);
            }
            if (err.equals("")) {
                if (tuttiRadioButton.isSelected()) {
                    elenco=FunzioniDB.leggiPersone();
                } else if (acquirentiRadioButton.isSelected()) {
                    elenco=FunzioniDB.leggiAcquirenti();
                    } else  {
                        elenco=FunzioniDB.leggiVenditori();
                            }
                aggiornaElenco();
                svuotaDettagli();
            } else {
                JOptionPane.showMessageDialog(null, err, "Errore!", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, err, "Errore!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void aggiornaElenco() {
        elencoTable.setModel(new ElencoPersoneTableModel(elenco.iterator()));
        svuotaDettagli();
    }
    
    private void aggiornaDettagli(Persona selezionata) {
        nomeTextField.setText(selezionata.getNome());
        cognomeTextField.setText(selezionata.getCognome());
        descrizioneTextField.setText(selezionata.getDenominazione());
        indirizzoTextField.setText(selezionata.getIndirizzo());
        emailTextField.setText(selezionata.getEmail());
        cellulareTextField.setText(selezionata.getTelefono());
        acquirenteCheckBox.setSelected(selezionata.getAcquirente().equals("S"));
        venditoreCheckBox.setSelected(selezionata.getVenditore().equals("S"));
        selId=selezionata.getId();
    }
    
    private void svuotaDettagli() {
        nomeTextField.setText("");
        cognomeTextField.setText("");
        descrizioneTextField.setText("");
        indirizzoTextField.setText("");
        emailTextField.setText("");
        cellulareTextField.setText("");
        acquirenteCheckBox.setSelected(false);
        venditoreCheckBox.setSelected(false);
        selId=-1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anagrafiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anagrafiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anagrafiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anagrafiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anagrafiche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox acquirenteCheckBox;
    private javax.swing.JRadioButton acquirentiRadioButton;
    private javax.swing.JButton annullaButton;
    private javax.swing.JButton cancellaButton;
    private javax.swing.JTextField cellulareTextField;
    private javax.swing.JTextField cognomeTextField;
    private javax.swing.JTextField descrizioneTextField;
    private javax.swing.JTable elencoTable;
    private javax.swing.JTextField emailTextField;
    private javax.swing.ButtonGroup filtraPersoneButtonGroup;
    private javax.swing.JTextField indirizzoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JButton nuovoButton;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton tuttiRadioButton;
    private javax.swing.JCheckBox venditoreCheckBox;
    private javax.swing.JRadioButton venditoriRadioButton;
    // End of variables declaration//GEN-END:variables

    

}
