/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package magazzinofumetti;

import java.util.HashSet;
import java.util.Iterator;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;

/**
  * @author elsoft
 */
public class NuovoLottoAcquisto extends javax.swing.JFrame {

    private LottoAcquisto lotto;
    private HashSet<Persona> persone;

    /**
     * Creates new form NuovoLottoDialog
     */
    public NuovoLottoAcquisto() {
        super();
        initComponents();
        lotto=new LottoAcquisto();
        persone=new HashSet();
        inizializzaVenditori();
        inizializzaCaseEditrici();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        descrizioneTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aggiungiAlboButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        elencoAlbiTable = new javax.swing.JTable();
        eliminaAlboButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        descrizioneAlboTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        costoAlboTextField = new javax.swing.JTextField();
        prezzoAlboTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numeroAlboTextField = new javax.swing.JTextField();
        casaEditriceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipologiaTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        annullaButton = new javax.swing.JButton();
        venditoreCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        noteTextArea = new javax.swing.JTextArea();
        costoLottoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dataAcquistoLotto = new org.jdesktop.swingx.JXDatePicker();
        costoAlbiButton = new javax.swing.JButton();
        costoLotto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Descrizione lotto");

        descrizioneTextField.setNextFocusableComponent(venditoreCombo);

        jLabel3.setText("Venditore");

        jLabel4.setText("Costo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Albi"));

        aggiungiAlboButton.setText("Aggiungi");
        aggiungiAlboButton.setNextFocusableComponent(descrizioneAlboTextField);
        aggiungiAlboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiAlboButtonActionPerformed(evt);
            }
        });

        elencoAlbiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrizione", "Costo", "Prezzo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        elencoAlbiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elencoAlbiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(elencoAlbiTable);

        eliminaAlboButton.setText("Elimina");
        eliminaAlboButton.setEnabled(false);
        eliminaAlboButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaAlboButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Descrizione");

        descrizioneAlboTextField.setNextFocusableComponent(numeroAlboTextField);

        jLabel6.setText("Prezzo");

        jLabel7.setText("Costo");

        costoAlboTextField.setNextFocusableComponent(prezzoAlboTextField);

        prezzoAlboTextField.setNextFocusableComponent(aggiungiAlboButton);

        jLabel8.setText("Numero");

        numeroAlboTextField.setNextFocusableComponent(costoAlboTextField);

        jLabel9.setText("Editore");

        jLabel10.setText("Tipologia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numeroAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(costoAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prezzoAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(casaEditriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                            .addComponent(descrizioneAlboTextField)
                            .addComponent(tipologiaTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminaAlboButton)
                            .addComponent(aggiungiAlboButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {aggiungiAlboButton, eliminaAlboButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casaEditriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tipologiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(descrizioneAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aggiungiAlboButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(costoAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(prezzoAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminaAlboButton)
                    .addComponent(jLabel8)
                    .addComponent(numeroAlboTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        annullaButton.setText("Annulla");
        annullaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaButtonActionPerformed(evt);
            }
        });

        venditoreCombo.setNextFocusableComponent(costoLottoTextField);

        noteTextArea.setColumns(20);
        noteTextArea.setRows(5);
        noteTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Note"));
        jScrollPane2.setViewportView(noteTextArea);

        costoLottoTextField.setNextFocusableComponent(dataAcquistoLotto);

        jLabel1.setText("Acquistato il");

        dataAcquistoLotto.setNextFocusableComponent(noteTextArea);

        costoAlbiButton.setText("Costo albi");
        costoAlbiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoAlbiButtonActionPerformed(evt);
            }
        });

        costoLotto.setText("Costo lotto");
        costoLotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoLottoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descrizioneTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annullaButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(costoLottoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dataAcquistoLotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(venditoreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(costoAlbiButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(costoLotto)))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {annullaButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descrizioneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(venditoreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(costoLottoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dataAcquistoLotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoAlbiButton)
                            .addComponent(costoLotto)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(annullaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annullaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annullaButtonActionPerformed
        svuota();
        this.dispose();
    }//GEN-LAST:event_annullaButtonActionPerformed

    private void aggiungiAlboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiAlboButtonActionPerformed
        float costo=0,prezzo=0,err=0;
        try {
            if (!"".equals(costoAlboTextField.getText().trim())){
                costo=Float.parseFloat(costoAlboTextField.getText());
                if (costo<0) throw new Exception("CostoNegativo");
            } else {
            }
        } catch (Exception ex){
            javax.swing.JOptionPane.showMessageDialog(this, "Costo errato");
            err++;
        }
        try {
            if (!"".equals(prezzoAlboTextField.getText().trim())){
                prezzo=Float.parseFloat(prezzoAlboTextField.getText());
                if (prezzo<0) throw new Exception("PrezzoNegativo");
            } else {
            }
        } catch (Exception ex){
            javax.swing.JOptionPane.showMessageDialog(this, "Prezzo errato");
            err++;
        }
        if (err==0){
            lotto.addAlbo(new Albo(casaEditriceTextField.getText(),tipologiaTextField.getText(),descrizioneAlboTextField.getText(),numeroAlboTextField.getText(),costo,prezzo));
            pulisciCampiAlbo();
            aggiornaTabellaAlbi();
        }
    }//GEN-LAST:event_aggiungiAlboButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String err="";
        float costo=0;
        err+=(descrizioneTextField.getText().trim().equals(""))?"Manca la descrizione del lotto\n":"";
        if (costoLottoTextField.getText().equals("")){
            err+="Manca il costo del lotto\n";
        } else {
            costo=Float.parseFloat(costoLottoTextField.getText());
            if (costo<0){
                err+="Costo negativo\n";
            }
        }
        if (!err.equals("")){
            JOptionPane.showMessageDialog(this,err);
        } else {
            lotto.setDescrizione(descrizioneTextField.getText().trim());
            lotto.setTotale(costo);
            lotto.setVenditore((Persona)venditoreCombo.getSelectedItem());
            lotto.setData(dataAcquistoLotto.getDate());
            lotto.setNote(noteTextArea.getText());
            if (FunzioniDB.inserisciLottoAcquisto(lotto)==true){
                svuota();
                this.dispose();
            }
            else
                JOptionPane.showMessageDialog(this,"Inserimento non riuscito");
        }
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void costoAlbiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoAlbiButtonActionPerformed
        if (!costoLottoTextField.getText().equals("")&&lotto.getNumAlbi()>0){
            float costoAlbo=Float.parseFloat(costoLottoTextField.getText())/lotto.getNumAlbi();
            lotto.assegnaCostoAlbi(costoAlbo);
            aggiornaTabellaAlbi();
        }
    }//GEN-LAST:event_costoAlbiButtonActionPerformed

    private void costoLottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoLottoActionPerformed
        lotto.calcolaTotale();
        costoLottoTextField.setText(String.valueOf(lotto.getTotale()));
    }//GEN-LAST:event_costoLottoActionPerformed

    private void elencoAlbiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elencoAlbiTableMouseClicked
        if (elencoAlbiTable.getSelectedRow()>-1){
            eliminaAlboButton.setEnabled(true);
        }
    }//GEN-LAST:event_elencoAlbiTableMouseClicked

    private void eliminaAlboButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaAlboButtonActionPerformed
        Albo tmpAlbo=(Albo)elencoAlbiTable.getModel().getValueAt(elencoAlbiTable.getSelectedRow(), 0);
        lotto.removeAlbo(tmpAlbo);
        eliminaAlboButton.setEnabled(false);
        aggiornaTabellaAlbi();
    }//GEN-LAST:event_eliminaAlboButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuovoLottoAcquisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuovoLottoAcquisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuovoLottoAcquisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuovoLottoAcquisto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuovoLottoAcquisto dialog = new NuovoLottoAcquisto();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggiungiAlboButton;
    private javax.swing.JButton annullaButton;
    private javax.swing.JTextField casaEditriceTextField;
    private javax.swing.JButton costoAlbiButton;
    private javax.swing.JTextField costoAlboTextField;
    private javax.swing.JButton costoLotto;
    private javax.swing.JTextField costoLottoTextField;
    private org.jdesktop.swingx.JXDatePicker dataAcquistoLotto;
    private javax.swing.JTextField descrizioneAlboTextField;
    private javax.swing.JTextField descrizioneTextField;
    private javax.swing.JTable elencoAlbiTable;
    private javax.swing.JButton eliminaAlboButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea noteTextArea;
    private javax.swing.JTextField numeroAlboTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField prezzoAlboTextField;
    private javax.swing.JTextField tipologiaTextField;
    private javax.swing.JComboBox<Persona> venditoreCombo;
    // End of variables declaration//GEN-END:variables

    void svuota() {
        costoLottoTextField.setText("");
        descrizioneTextField.setText("");
        //venditoreCombo.setSelectedIndex(0);
        lotto.svuotaAlbi();
        aggiornaTabellaAlbi();
    }

    private void aggiornaTabellaAlbi() {
        Iterator<Albo> albi=lotto.getAlbiDisponibili().iterator();
        elencoAlbiTable.setModel(new ElencoAlbiModel(albi));
//        while (albi.hasNext()){
//            Albo albo=albi.next();
//            System.out.println(albo);
//        }
    }

    private void inizializzaVenditori() {
        persone=FunzioniDB.leggiVenditori();
        Iterator<Persona> personeIter = persone.iterator();
        while (personeIter.hasNext()){
            Persona tmpPer=personeIter.next();
            venditoreCombo.addItem(tmpPer);
        }
        
    }

    private void pulisciCampiAlbo() {
        descrizioneAlboTextField.setText("");
        costoAlboTextField.setText("");
        prezzoAlboTextField.setText("");
        numeroAlboTextField.setText("");
        casaEditriceTextField.setText("");
        tipologiaTextField.setText("");
    }

    private void inizializzaCaseEditrici() {
        String[] data = {"one", "two", "three", "four"}; 
        JList dataList = new JList(data); 
        //AutoCompleteDecorator.decorate(dataList, casaEditriceTextField, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
    }

}
